name = "CensusData"
uuid = "b405a967-5e0f-48b9-866e-fec9f8ca74ad"
authors = ["Michael Johnson"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
